upstream auth_service_http {
    server auth-service:8082;
}

upstream auth_service_grpc {
    server auth-service:50052;
}

upstream user_service {
    server user-service:50051;
}

server {
    listen 80;
    server_name localhost;

    location /auth {
        proxy_pass http://auth_service_http;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # REST API: Обработка форм от фронтенда (fetch)
    location /api/auth/ {
        proxy_pass http://auth_service_http;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API: user-service (REST)
    location /api/users/ {
        proxy_pass http://user_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth.YourServiceName/ {
        grpc_pass grpc://auth_service_grpc;
        grpc_set_header Host $host;
    }

    # gRPC - user-service
    location /user.AlhelisService/ {
        grpc_pass grpc://user_service;
        grpc_set_header Host $host;
    }

    # Статика и HTML
    location /dashboard {
        root /usr/share/nginx/html;
        try_files /dashboard.html =404;
    }

location / {
        root /usr/share/nginx/html;
        index dashboard.html;        
        try_files $uri $uri/ =404;    
    }
}