upstream auth_service_http {
    server auth-service:8082;
}

upstream auth_service_grpc {
    server auth-service:50052;
}

upstream user_service {
    server user-service:50051;
}

server {
    listen 80;
    server_name localhost;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location /auth {
        proxy_pass http://auth_service_http;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/auth/ {
        proxy_pass http://auth_service_http;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Set-Cookie;
    }

    location /api/users/ {
        proxy_pass http://user_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Authorization $http_authorization;
    }

    location /auth.YourServiceName/ {
        grpc_pass grpc://auth_service_grpc;
        grpc_set_header Host $host;
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
    }

    location /user.AlhelisService/ {
        grpc_pass grpc://user_service;
        grpc_set_header Host $host;
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
    }

    location /dashboard {
        root /usr/share/nginx/html;
        try_files /dashboard.html =404;
    }

    location / {
        root /usr/share/nginx/html;
        index dashboard.html;
        try_files $uri $uri/ =404;
    }
}