// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: alhelis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceFrom     float64                `protobuf:"fixed64,4,opt,name=price_from,json=priceFrom,proto3" json:"price_from,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_alhelis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetPriceFrom() float64 {
	if x != nil {
		return x.PriceFrom
	}
	return 0
}

func (x *Service) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ListServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceRequest) Reset() {
	*x = ListServiceRequest{}
	mi := &file_alhelis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceRequest) ProtoMessage() {}

func (x *ListServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceRequest.ProtoReflect.Descriptor instead.
func (*ListServiceRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{1}
}

type ListServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceResponse) Reset() {
	*x = ListServiceResponse{}
	mi := &file_alhelis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceResponse) ProtoMessage() {}

func (x *ListServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceResponse.ProtoReflect.Descriptor instead.
func (*ListServiceResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{2}
}

func (x *ListServiceResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_alhelis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_alhelis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_alhelis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_alhelis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_alhelis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_alhelis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateOrderRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServiceId   string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Area        float64                `protobuf:"fixed64,3,opt,name=area,proto3" json:"area,omitempty"`
	// на случай пустого пользователя
	GuestName     string `protobuf:"bytes,4,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail    string `protobuf:"bytes,5,opt,name=guest_email,json=guestEmail,proto3" json:"guest_email,omitempty"`
	GuestPhone    string `protobuf:"bytes,6,opt,name=guest_phone,json=guestPhone,proto3" json:"guest_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_alhelis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateOrderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrderRequest) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *CreateOrderRequest) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *CreateOrderRequest) GetGuestEmail() string {
	if x != nil {
		return x.GuestEmail
	}
	return ""
}

func (x *CreateOrderRequest) GetGuestPhone() string {
	if x != nil {
		return x.GuestPhone
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_alhelis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ServiceTitle  string                 `protobuf:"bytes,3,opt,name=service_title,json=serviceTitle,proto3" json:"service_title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_alhelis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{11}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetServiceTitle() string {
	if x != nil {
		return x.ServiceTitle
	}
	return ""
}

func (x *Order) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListMyOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersRequest) Reset() {
	*x = ListMyOrdersRequest{}
	mi := &file_alhelis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersRequest) ProtoMessage() {}

func (x *ListMyOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrdersRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{12}
}

type ListMyOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersResponse) Reset() {
	*x = ListMyOrdersResponse{}
	mi := &file_alhelis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersResponse) ProtoMessage() {}

func (x *ListMyOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListMyOrdersResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{13}
}

func (x *ListMyOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_alhelis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{14}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_alhelis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{15}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProfileResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_alhelis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_alhelis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Favorite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Favorite) Reset() {
	*x = Favorite{}
	mi := &file_alhelis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Favorite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorite) ProtoMessage() {}

func (x *Favorite) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorite.ProtoReflect.Descriptor instead.
func (*Favorite) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{18}
}

func (x *Favorite) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesRequest) Reset() {
	*x = ListFavoritesRequest{}
	mi := &file_alhelis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesRequest) ProtoMessage() {}

func (x *ListFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{19}
}

type ListFavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorites     []*Favorite            `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesResponse) Reset() {
	*x = ListFavoritesResponse{}
	mi := &file_alhelis_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesResponse) ProtoMessage() {}

func (x *ListFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesResponse.ProtoReflect.Descriptor instead.
func (*ListFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{20}
}

func (x *ListFavoritesResponse) GetFavorites() []*Favorite {
	if x != nil {
		return x.Favorites
	}
	return nil
}

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_alhelis_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{21}
}

func (x *AddFavoriteRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type AddFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_alhelis_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{22}
}

func (x *AddFavoriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_alhelis_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveFavoriteRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type RemoveFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteResponse) Reset() {
	*x = RemoveFavoriteResponse{}
	mi := &file_alhelis_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteResponse) ProtoMessage() {}

func (x *RemoveFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteResponse.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveFavoriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_alhelis_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{25}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_alhelis_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alhelis_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_alhelis_proto_rawDescGZIP(), []int{26}
}

func (x *CreateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_alhelis_proto protoreflect.FileDescriptor

const file_alhelis_proto_rawDesc = "" +
	"\n" +
	"\ralhelis.proto\x12\aalhelis\"\x8d\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"price_from\x18\x04 \x01(\x01R\tpriceFrom\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\"\x14\n" +
	"\x12ListServiceRequest\"C\n" +
	"\x13ListServiceResponse\x12,\n" +
	"\bservices\x18\x01 \x03(\v2\x10.alhelis.ServiceR\bservices\"#\n" +
	"\x11GetServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetServiceResponse\x12*\n" +
	"\aservice\x18\x01 \x01(\v2\x10.alhelis.ServiceR\aservice\"m\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"E\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xca\x01\n" +
	"\x12CreateOrderRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04area\x18\x03 \x01(\x01R\x04area\x12\x1d\n" +
	"\n" +
	"guest_name\x18\x04 \x01(\tR\tguestName\x12\x1f\n" +
	"\vguest_email\x18\x05 \x01(\tR\n" +
	"guestEmail\x12\x1f\n" +
	"\vguest_phone\x18\x06 \x01(\tR\n" +
	"guestPhone\";\n" +
	"\x13CreateOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.alhelis.OrderR\x05order\"\x95\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rservice_title\x18\x03 \x01(\tR\fserviceTitle\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x15\n" +
	"\x13ListMyOrdersRequest\">\n" +
	"\x14ListMyOrdersResponse\x12&\n" +
	"\x06orders\x18\x01 \x03(\v2\x0e.alhelis.OrderR\x06orders\"\x13\n" +
	"\x11GetProfileRequest\"W\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"@\n" +
	"\x14UpdateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"1\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\bFavorite\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\x16\n" +
	"\x14ListFavoritesRequest\"H\n" +
	"\x15ListFavoritesResponse\x12/\n" +
	"\tfavorites\x18\x01 \x03(\v2\x11.alhelis.FavoriteR\tfavorites\"3\n" +
	"\x12AddFavoriteRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"/\n" +
	"\x13AddFavoriteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x15RemoveFavoriteRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"2\n" +
	"\x16RemoveFavoriteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"1\n" +
	"\x15CreateProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x85\a\n" +
	"\x0eAlhelisService\x12H\n" +
	"\vListService\x12\x1b.alhelis.ListServiceRequest\x1a\x1c.alhelis.ListServiceResponse\x12E\n" +
	"\n" +
	"GetService\x12\x1a.alhelis.GetServiceRequest\x1a\x1b.alhelis.GetServiceResponse\x12?\n" +
	"\bRegister\x12\x18.alhelis.RegisterRequest\x1a\x19.alhelis.RegisterResponse\x126\n" +
	"\x05Login\x12\x15.alhelis.LoginRequest\x1a\x16.alhelis.LoginResponse\x12H\n" +
	"\vCreateOrder\x12\x1b.alhelis.CreateOrderRequest\x1a\x1c.alhelis.CreateOrderResponse\x12K\n" +
	"\fListMyOrders\x12\x1c.alhelis.ListMyOrdersRequest\x1a\x1d.alhelis.ListMyOrdersResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.alhelis.GetProfileRequest\x1a\x1b.alhelis.GetProfileResponse\x12N\n" +
	"\rCreateProfile\x12\x1d.alhelis.CreateProfileRequest\x1a\x1e.alhelis.CreateProfileResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.alhelis.UpdateProfileRequest\x1a\x1e.alhelis.UpdateProfileResponse\x12N\n" +
	"\rListFavorites\x12\x1d.alhelis.ListFavoritesRequest\x1a\x1e.alhelis.ListFavoritesResponse\x12H\n" +
	"\vAddFavorite\x12\x1b.alhelis.AddFavoriteRequest\x1a\x1c.alhelis.AddFavoriteResponse\x12Q\n" +
	"\x0eRemoveFavorite\x12\x1e.alhelis.RemoveFavoriteRequest\x1a\x1f.alhelis.RemoveFavoriteResponseB\x0eZ\famelli/protob\x06proto3"

var (
	file_alhelis_proto_rawDescOnce sync.Once
	file_alhelis_proto_rawDescData []byte
)

func file_alhelis_proto_rawDescGZIP() []byte {
	file_alhelis_proto_rawDescOnce.Do(func() {
		file_alhelis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alhelis_proto_rawDesc), len(file_alhelis_proto_rawDesc)))
	})
	return file_alhelis_proto_rawDescData
}

var file_alhelis_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_alhelis_proto_goTypes = []any{
	(*Service)(nil),                // 0: alhelis.Service
	(*ListServiceRequest)(nil),     // 1: alhelis.ListServiceRequest
	(*ListServiceResponse)(nil),    // 2: alhelis.ListServiceResponse
	(*GetServiceRequest)(nil),      // 3: alhelis.GetServiceRequest
	(*GetServiceResponse)(nil),     // 4: alhelis.GetServiceResponse
	(*RegisterRequest)(nil),        // 5: alhelis.RegisterRequest
	(*RegisterResponse)(nil),       // 6: alhelis.RegisterResponse
	(*LoginRequest)(nil),           // 7: alhelis.LoginRequest
	(*LoginResponse)(nil),          // 8: alhelis.LoginResponse
	(*CreateOrderRequest)(nil),     // 9: alhelis.CreateOrderRequest
	(*CreateOrderResponse)(nil),    // 10: alhelis.CreateOrderResponse
	(*Order)(nil),                  // 11: alhelis.Order
	(*ListMyOrdersRequest)(nil),    // 12: alhelis.ListMyOrdersRequest
	(*ListMyOrdersResponse)(nil),   // 13: alhelis.ListMyOrdersResponse
	(*GetProfileRequest)(nil),      // 14: alhelis.GetProfileRequest
	(*GetProfileResponse)(nil),     // 15: alhelis.GetProfileResponse
	(*UpdateProfileRequest)(nil),   // 16: alhelis.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 17: alhelis.UpdateProfileResponse
	(*Favorite)(nil),               // 18: alhelis.Favorite
	(*ListFavoritesRequest)(nil),   // 19: alhelis.ListFavoritesRequest
	(*ListFavoritesResponse)(nil),  // 20: alhelis.ListFavoritesResponse
	(*AddFavoriteRequest)(nil),     // 21: alhelis.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),    // 22: alhelis.AddFavoriteResponse
	(*RemoveFavoriteRequest)(nil),  // 23: alhelis.RemoveFavoriteRequest
	(*RemoveFavoriteResponse)(nil), // 24: alhelis.RemoveFavoriteResponse
	(*CreateProfileRequest)(nil),   // 25: alhelis.CreateProfileRequest
	(*CreateProfileResponse)(nil),  // 26: alhelis.CreateProfileResponse
}
var file_alhelis_proto_depIdxs = []int32{
	0,  // 0: alhelis.ListServiceResponse.services:type_name -> alhelis.Service
	0,  // 1: alhelis.GetServiceResponse.service:type_name -> alhelis.Service
	11, // 2: alhelis.CreateOrderResponse.order:type_name -> alhelis.Order
	11, // 3: alhelis.ListMyOrdersResponse.orders:type_name -> alhelis.Order
	18, // 4: alhelis.ListFavoritesResponse.favorites:type_name -> alhelis.Favorite
	1,  // 5: alhelis.AlhelisService.ListService:input_type -> alhelis.ListServiceRequest
	3,  // 6: alhelis.AlhelisService.GetService:input_type -> alhelis.GetServiceRequest
	5,  // 7: alhelis.AlhelisService.Register:input_type -> alhelis.RegisterRequest
	7,  // 8: alhelis.AlhelisService.Login:input_type -> alhelis.LoginRequest
	9,  // 9: alhelis.AlhelisService.CreateOrder:input_type -> alhelis.CreateOrderRequest
	12, // 10: alhelis.AlhelisService.ListMyOrders:input_type -> alhelis.ListMyOrdersRequest
	14, // 11: alhelis.AlhelisService.GetProfile:input_type -> alhelis.GetProfileRequest
	25, // 12: alhelis.AlhelisService.CreateProfile:input_type -> alhelis.CreateProfileRequest
	16, // 13: alhelis.AlhelisService.UpdateProfile:input_type -> alhelis.UpdateProfileRequest
	19, // 14: alhelis.AlhelisService.ListFavorites:input_type -> alhelis.ListFavoritesRequest
	21, // 15: alhelis.AlhelisService.AddFavorite:input_type -> alhelis.AddFavoriteRequest
	23, // 16: alhelis.AlhelisService.RemoveFavorite:input_type -> alhelis.RemoveFavoriteRequest
	2,  // 17: alhelis.AlhelisService.ListService:output_type -> alhelis.ListServiceResponse
	4,  // 18: alhelis.AlhelisService.GetService:output_type -> alhelis.GetServiceResponse
	6,  // 19: alhelis.AlhelisService.Register:output_type -> alhelis.RegisterResponse
	8,  // 20: alhelis.AlhelisService.Login:output_type -> alhelis.LoginResponse
	10, // 21: alhelis.AlhelisService.CreateOrder:output_type -> alhelis.CreateOrderResponse
	13, // 22: alhelis.AlhelisService.ListMyOrders:output_type -> alhelis.ListMyOrdersResponse
	15, // 23: alhelis.AlhelisService.GetProfile:output_type -> alhelis.GetProfileResponse
	26, // 24: alhelis.AlhelisService.CreateProfile:output_type -> alhelis.CreateProfileResponse
	17, // 25: alhelis.AlhelisService.UpdateProfile:output_type -> alhelis.UpdateProfileResponse
	20, // 26: alhelis.AlhelisService.ListFavorites:output_type -> alhelis.ListFavoritesResponse
	22, // 27: alhelis.AlhelisService.AddFavorite:output_type -> alhelis.AddFavoriteResponse
	24, // 28: alhelis.AlhelisService.RemoveFavorite:output_type -> alhelis.RemoveFavoriteResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_alhelis_proto_init() }
func file_alhelis_proto_init() {
	if File_alhelis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alhelis_proto_rawDesc), len(file_alhelis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alhelis_proto_goTypes,
		DependencyIndexes: file_alhelis_proto_depIdxs,
		MessageInfos:      file_alhelis_proto_msgTypes,
	}.Build()
	File_alhelis_proto = out.File
	file_alhelis_proto_goTypes = nil
	file_alhelis_proto_depIdxs = nil
}
